#ifndef MPMP19_GAP_LIST_HPP
#define MPMP19_GAP_LIST_HPP

#include <cstdint>
#include <cstddef>

namespace mpmp19 {

struct PrimeGapList {
    uint8_t* data_ = nullptr;   // compressed gap data
    size_t size_ = 0;    // number of bytes currently used
    size_t cap_ = 0;     // number of bytes allocated

    // 1024 = 2^10 is the maximum number of primes that can be generated by primesieve_generate_next_primes()
    // this is used when a prime_list is resized so that we guarantee within a single batch of primes
    // that a list only has to be resized at most one time
    static constexpr uint32_t MAX_PRIMES_PER_BATCH = 1U << 10;

    // used to indicate that the next gap is large and stored in the next 2 bytes
    static constexpr uint8_t LARGE_GAP_FLAG = 0xFFU;

    // used to check if a gap is large (uses 2 bytes) using a simple comparison
    static constexpr uint16_t LARGE_GAP_THRESHOLD = 0x100U;
    
    PrimeGapList() = default;
    ~PrimeGapList();

    void reset();
    void reserve(size_t cap);
    void reserve_full_batch();
    void push(uint16_t gap);
};

}   // namespace

#endif