// mpmp19_gap_list.h — prime gap storage, 16-bit compressed gaps
// Not a general purpose container — designed specifically for mpmp19's
// batch-write pattern where capacity is checked once per primesieve batch
// and data is written directly without per-element bounds checking.

#ifndef MPMP19_GAP_LIST_HPP
#define MPMP19_GAP_LIST_HPP

#include <cstdint>
#include <cstddef>

namespace mpmp19 {

struct PrimeGapList {
    uint8_t* data = nullptr;   // compressed gap data
    size_t length = 0;   // number of elements in list (not bytes, since some gaps take 3 bytes)
    size_t cap = 0;     // allocated capacity in elements

    // 1024 = 2^10 is the maximum number of primes that can be generated by primesieve_generate_next_primes()
    // this is used when a prime_list is resized so that we guarantee within a single batch of primes
    // that a list only has to be resized at most one time
    static constexpr uint32_t MAX_PRIMES_PER_BATCH = 1U << 10;

    static constexpr uint8_t LARGE_GAP_FLAG = 255;   // used to indicate that the next gap is large and stored in the next 2 bytes

    static constexpr uint16_t LARGE_GAP_MASK = 0xFF00U;   // used to check if a gap is large by checking whether the largest byte is non zero

    static constexpr uint16_t LARGE_GAP_THRESHOLD = 0x100U;
    
    PrimeGapList() = default;
    ~PrimeGapList();

    void reset();
    void reserve(size_t cap_);
    void reserve_full_batch();
    void push(uint16_t gap);
};

}   // namespace

#endif